# fly.toml app configuration file generated for hexcode on 2023-10-11T15:51:57+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hexcode"
primary_region = "mad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/web/dist/assets"
  url_prefix = "/assets"

[[files]]
  guest_path = "/web/dist/index.html"
  local_path = "/web/dist/index.html"